### ISSUE TITLE
Error While Connecting

### ISSUE THREAD

**Issue by nortbird** [zerodytrash/TikTok-Chat-Reader#12]
I got this error while trying to run the chat reader locally, what should I do? 

New connection from origin http://localhost:8081/
WRAPPER @@rrpas: Error event triggered: Error while connecting, Error: Missing cursor in initial fetch response.
{
  info: 'Error while connecting',
  exception: Error: Missing cursor in initial fetch response.
      at WebcastPushConnection._fetchRoomData2 (D:\Downloads\tiktok\TikTok-Chat-Reader-main\node_modules\tiktok-live-connector\dist\index.js:503:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async WebcastPushConnection.connect (D:\Downloads\tiktok\TikTok-Chat-Reader-main\node_modules\tiktok-live-connector\dist\index.js:268:7)
}
WRAPPER @@rrpas: Connection failed, Error: Missing cursor in initial fetch response.

**Comment by tommy50773** [comment]
This tool doesn't seem to work properly:
![image](https://user-images.githubusercontent.com/89059343/181904255-5ed2387d-9ddc-4beb-bc20-2ed05d8df0bb.png)

**Comment by zerodytrash** [comment]
Have updated the library. Test again.
