### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by iincognito15** [zerodytrash/TikTok-Chat-Reader#36]
It hasn't worked locally for 3 days, it shows this error in the terminal:

New connection from origin http://localhost:8091/
WRAPPER @@Pepit@123: Error event triggered: Error while connecting, Error: Failed to retrieve room_id from page source. Parse Error
{ info: 'Error while connecting',
   exception:
    Error: Failed to retrieve room_id from page source. Parse Error
        at WebcastPushConnection._retrieveRoomId2 (/home/pepito/TikTok-Chat-Reader/node_modules/tiktok-live-connector/dist/index.js:501:11)
        at process._tickCallback (internal/process/next_tick.js:68:7) }
WRAPPER @@Pepit@123: Connection failed, Error: Failed to retrieve room_id from page source. Parse Error.

And in the browser:

Error: Failed to retrieve room_id from page source. Parse Error

Any solution?

**Comment by minhduc152001** [comment]
do you know how to fix this error?
