### ISSUE TITLE
Cannot find module 'node:events'

### ISSUE THREAD

**Issue by ratara** [zerodytrash/TikTok-Chat-Reader#47]
Hi,
I tried to follow the 5 installation steps. Everything worked besides step 5) starting the server.js.
I get the following error output:
`
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/ralf/Dokumente/work/TikTok-Chat-Reader/node_modules/tiktok-live-connector/dist/index.js
- /home/ralf/Dokumente/work/TikTok-Chat-Reader/node_modules/tiktok-live-connector/index.js
- /home/ralf/Dokumente/work/TikTok-Chat-Reader/connectionWrapper.js
- /home/ralf/Dokumente/work/TikTok-Chat-Reader/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ralf/Dokumente/work/TikTok-Chat-Reader/node_modules/tiktok-live-connector/dist/index.js:23:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ralf/Dokumente/work/TikTok-Chat-Reader/node_modules/tiktok-live-connector/dist/index.js',
    '/home/ralf/Dokumente/work/TikTok-Chat-Reader/node_modules/tiktok-live-connector/index.js',
    '/home/ralf/Dokumente/work/TikTok-Chat-Reader/connectionWrapper.js',
    '/home/ralf/Dokumente/work/TikTok-Chat-Reader/server.js'
  ]
}
`
I tried to start it via browser and index.html and this worked. But i need to run the server..

OS: Ubuntu 22.04.4 LTS 64bit
Standard nodejs: v12.22.9

Any ideas? Thanks in advance.

**Comment by ratara** [comment]
Ok, I got infos that my node version is too old. I tried to update node and failed. So i decided to deinstall it and try again. After deinstalling npm it suddenly worked and my node version is out of nowhere v21.7.1.

Now "node server.js" works fine.
